# Generated by Django 5.1.3 on 2024-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_certificatetype_personcertificate_delete_certificate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personcertificate',
            constraint=models.UniqueConstraint(fields=('person', 'certificate_type'), name='unique_person_certificate'),
        ),
    ]
